language: python
python:
  - 2.6
  - 2.7

env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3

install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - sed -ie "s#test-4.2.x.cfg#travis-$PLONE_VERSION.x.cfg#" buildout.cfg
  - make version=$TRAVIS_PYTHON_VERSION .installed.cfg

script:
  - make tests

after_success:
 - pip install python-coveralls==2.4.0
 - coveralls

notifications:
  irc:
    - "irc.freenode.org#sprint"
  template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"