language: python
python:
  - 2.6
  - 2.7

env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3

install:
  - pip remove distribute
  - pip install --upgrade setuptools
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - sed -ie "s#test-4.2.x.cfg#travis-$PLONE_VERSION.x.cfg#" buildout.cfg
  - make version=$TRAVIS_PYTHON_VERSION .installed.cfg

script:
  - make tests

notifications:
  irc:
    - "irc.freenode.org#sprint"
